openapi: 3.0.0
info:
  title: Pandora
  version: 1.0.0
paths:
  /exec:
    post:
      summary: Executes a shell command.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: The shell command to execute.
      responses:
        '200':
          description: The command was executed successfully.
  /getGuide:
    get:
      summary: Returns the LLM's guide to effective text editing.
      responses:
        '200':
          description: The guide was returned successfully.
  /writeFile:
    post:
      summary: Writes content to a file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: The path of the file to write to.
                content:
                  type: string
                  description: The content to write to the file.
                force:
                  type: boolean
                  description: If true, overwrite the file if it exists.
      responses:
        '200':
          description: The file was written successfully.