openapi: 3.0.0
info:
  title: Pandora
  description: Pandora is a lightweight and powerful tool for interacting with the file system and executing shell commands.
  version: 1.0.0
paths:
  /exec:
    post:
      summary: Executes a shell command.
      operationId: exec
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: Shell command to execute. Eg `ls .`, `curl foo`, `apt-get install foo`
                guideFollowed:
                  type: bool
                  description: Whether the guide is being followed. Must be true
      responses:
        '200':
          description: The command was executed successfully.
  /getGuide:
    get:
      operationId: getGuide
      summary: Returns the LLM's guide to this plugin. This MUST be read and understood.
      responses:
        '200':
          description: The guide was returned successfully.
  /writeFile:
    post:
      operationId: writeFile
      summary: Writes content to a file.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filePath:
                  type: string
                  description: The path of the file to write to.
                content:
                  type: string
                  description: The content to write to the file.
                force:
                  type: boolean
                  description: If true, overwrite the file if it exists.
                appendNewline:
                  description: Append a newline to the end of the file.
                  type: boolean
                permissions:
                  description: The file permissions to set, in octal format with leading 0 (e.g., "0644").
                  required: false
                  type: string
                  pattern: '^[0-7]{4}$'
      responses:
        '200':
          description: The file was written successfully.